### ISSUE TITLE
Remove dependency on the `lang-common` S3 bucket (vendor buildpack-stdlib)

### ISSUE THREAD

**Issue by edmorley** [crazyantlabs/heroku-buildpack-cli-plugin-cron#2]
Hi

I noticed this buildpack has a build-time dependency on one of our legacy/unmaintained libraries and corresponding S3 bucket:
https://github.com/crazyantlabs/heroku-buildpack-cli-plugin-cron/blob/dfbe763efbdbefca44c8e98ef38bb6f802cc79a5/bin/compile#L13

I would recommend vendoring the file in this repo in case the S3 bucket is ever purged in the future :-)

Example vendoring change:
https://github.com/heroku/heroku-buildpack-scala/pull/202

The upstream library repo:
https://github.com/heroku/buildpack-stdlib

Best wishes,

Ed

**Comment by motymichaely** [comment]
@edmorley - Done. Thank you!
